---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022/8/12 15:33
---

t = {}
--print(type(t) == "table")

isEmpty = function(t)
    if type(t) == "table" then
        return t == nil or next(t) == nil
    end
    return t == nil
end
print(isEmpty(t))

-- 排序
t = {5,56,77,44,25,26}
table.sort(t)
print(unpack(t))

-- table最大值

function tableMax(t)
    local n
    for i,v in pairs(t) do
        if n == nil then
            n = v
        else if n < v then
            n = v
        end
        end
    end
    return n;
end

max = tableMax(t)

print(max)
table.sort(t)
max = t[#t]
print(max)