---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022/8/12 11:42
---

-- 变量定义
name = "名字"
age = 16

-- 局部变量 方法内部

function test()
    weight2 = 2;
    print(weight2)

end

print(test().weight2)